### ISSUE TITLE
Issues backing up IN when using a complex database password

### ISSUE THREAD

**Issue by Starbase12** [DrDBanner/inmanage#4] opened 2024-10-14 18:13 UTC
I run "./inmanage.sh backup && ./inmanage.sh update" as www-data user and got the following output:

`Environment check starts.
Self configuration found
No provision.
Creating backup directory.
./inmanage.sh: Zeile 542: GOA7on8N: Kommando nicht gefunden.
Failed to evaluate DB variables
`

I checked my .env file and found that right before the part "GOA7on8N" a "&" is mentioned as part of my complex password. In my .env file it's already written between "<password>" but somehow the script still can't detect it properly.

**Comment by Starbase12** [comment] 2024-10-14 18:30
Even when I removed the "&" it's not working because of "$" and/or "%". It seems to be somehow in general not support special characters. But instead of reporting or mention it properly it simply fails at different stages. To workaround this I just removed special characters from my .env file.

**Comment by DrDBanner** [comment] 2024-10-14 19:04
Thanks for reporting. I guess I’ll fix that 🤘🏼

**Comment by Starbase12** [comment] 2024-10-14 19:29
For my purpose I just set a new password and the issue is now workarouned. I will appreciate if you can make it work for the future. Maybe I'm not the only affected. But many thanks for your great work. It make backups and updates of IN so much more easy.

**Comment by DrDBanner** [comment] 2024-10-14 20:32
It just turned out, I have set % / in my password with no issue. well ... so, I have a hard time to guess where it breaks in your environment. I'll poke around a little. Thanks for the kind words.

**Comment by DrDBanner** [comment] 2024-10-15 18:08
Not able to reproduce here. Closing. If somebody rans into this issue again, workaround is mentioned above, and I'll retry on this issue.

**Comment by DrDBanner** [comment] 2024-10-15 18:08
closed

**Closed by DrDBanner** 2024-10-15 18:08 UTC

**Comment by CodeShakingSheep** [comment] 2025-09-28 15:42
I ran into this as well. I had a "&" right at the beginning of my DB password. After removing it, script ran fine again.

**Comment by DrDBanner** [comment] 2025-09-28 17:15
Thanks for reporting. Next version won’t this problem.
