### ISSUE TITLE
ln: failed to create symbolic link '/inmanage.sh': Permission denied

### ISSUE THREAD

**Issue by lakelounge** [DrDBanner/inmanage#5] opened 2024-12-12 14:41 UTC
trying to install on a Debian LXC-Container but the Script always drops an error: 
ln: failed to create symbolic link '/inmanage.sh': Permission denied
User/Group is www-data, Apache is running as this user.

**Comment by dieterth** [comment] 2024-12-13 15:56
Hi dros,
i do have the same error like lakelounge.
My plattform is debian 11 with php 8.3.14 and nginx, selfhosting.
Do you have any hint why this is happend?
I try to migrate from in 4.5.50 to the version 5*, there are so many questions and hints in the in forum about how to install in v5 on a selfhostet environment. I am a bit confused.

Best regards, Dieter

**Comment by dieterth** [comment] 2024-12-13 16:25
the exact error is:
.inmanage/.env.inmanage has been created and configured.
The symlink does not exist. Creating...
ln: die symbolische Verknüpfung '/inmanage.sh' konnte nicht angelegt werden: Keine Berechtigung

**Comment by lakelounge** [comment] 2024-12-13 16:29
@dieterth i figured out what exact link the inmanage.sh creates and created the symbolic link manually. In inmanage.sh is one if-possibility "link exists - do nothing". Result is the same error.

**Comment by DrDBanner** [comment] 2024-12-13 16:33
I didn't dive into it too deep but I'd assume your base directory is not owned by the group of your webserver user.

**Comment by lakelounge** [comment] 2024-12-13 16:36
at the end of my testing all apache volumes (from www on) have www-data as user

**Comment by dieterth** [comment] 2024-12-13 16:36
Hi DrDBanner,
even if i chose root as user instead of www-data, the script fails.
8-|

**Comment by DrDBanner** [comment] 2024-12-13 16:39
Then it's probably not an write issue per se but more like it's not able to determine the correct path. Maybe it tries to resolve outside of the filetree. Will need to test it within a vm. Will take a bit but I'll fix it if I am able to reproduce the problem.

**Comment by lakelounge** [comment] 2024-12-13 16:40
the inmanager.sh gets $INM_BASE_DIRECTORY from PWD. Is'nt target "/var/www/ninja.inmanage/inmanage.sh" with one missing slash between folder and dotted folder?

 # Handle symlink
        target="$INM_BASE_DIRECTORY.inmanage/inmanage.sh"
        link="$INM_BASE_DIRECTORY/inmanage.sh"

**Comment by DrDBanner** [comment] 2024-12-13 16:44
INM_BASE_DIRECTORY must have a trailing slash. It's literally stated during installation.

**Comment by lakelounge** [comment] 2024-12-13 16:53
what i mean is if there is a slash missing in your inmanage.sh 
in this line between ...DIRECTORY and ./nmanage/... in this line:
target="$INM_BASE_DIRECTORY.inmanage/inmanage.sh"

If you pwd you get /var/www/ninjadir … so you get /var/www/ninjadir.inmanage/inmanage.sh as target. Isn't there a slash missing? Between ninjadir and .inmanage?

**Comment by lakelounge** [comment] 2024-12-13 16:55
i thought you get it via $PWD … Didn't know that it must be entered … Sorry!

declare -A default_settings=(
    ["INM_BASE_DIRECTORY"]="$PWD/"

**Comment by DrDBanner** [comment] 2024-12-13 16:55
Not. Really. Currently it's meant to be that you fill the path in the variable WITH a trailing slash. Hence, the code is correct. Once I've time I'll cover this for automatic determination. But for now it must be set in the variable.

**Comment by lakelounge** [comment] 2024-12-13 17:11
Sorry, can do what i want and get an error … hmm …

**Comment by DrDBanner** [comment] 2024-12-13 17:13
will try with a vm. Then I'll see what the issue is ...

**Comment by dieterth** [comment] 2024-12-13 17:18
Tank You!

**Comment by lakelounge** [comment] 2024-12-13 17:25
Thank you very much!!!

**Comment by dieterth** [comment] 2024-12-13 18:55
if i call the script like this, it seems to be running:
sudo -u root bash -c "git clone https://github.com/DrDBanner/inmanage.git .inmanage && .inmanage/inmanage.sh"
 Just press [ENTER] to accept defaults. 

In shared hosting you may need to exclude tablespaces from mysqldump command. You need to keep it if your DB is very optimized for memory usage. Keep (Y) or Drop (N) [default: N]: 
Which directory contains your IN installation folder? Must have a trailing slash. [default: /srv/ninja5/]: 
How many backup files and update iterations to keep?  If set to 7 and backups occour on a daily basis you have 7 snapshots available. Make sure you have enough disk space. [default: 2]: 
Which shell should be used? In doubt, keep as is. [default: /usr/bin/bash]: 
Path to the PHP executable? In doubt, keep as is. [default: /usr/bin/php]: 
The user running the script? Should be the webserver user in most cases. Check twice if this value is set correct according to your webserver's setup. [default: www-data]: root
What is the installation directory name? Must be relative from $INM_BASE_DIRECTORY and can start with a . dot. [default: ./invoiceninja]: 
Provide value for INM_PROGRAM_NAME: [default: InvoiceNinja]: 
Provide value for INM_ARTISAN_STRING: [default: ${INM_PHP_EXECUTABLE} ${INM_BASE_DIRECTORY}${INM_INSTALLATION_DIRECTORY}/artisan]: 
Include database password in backup command? May be a security concern and may be visible for other server users while the task is running. If (N) the script assumes you have a secure and working .my.cnf file with your DB credentials and no password may get exposed to a task list. (Y/N) [default: N]: 
Where shall backups go? [default: ./_in_backups]: 
Provide value for INM_TEMP_DOWNLOAD_DIRECTORY: [default: ./._in_tempDownload]: 
Provide value for INM_COMPATIBILITY_VERSION: [default: 5+]: 
Provide value for INM_ENV_FILE: [default: ${INM_BASE_DIRECTORY}${INM_INSTALLATION_DIRECTORY}/.env]: 
.inmanage/.env.inmanage has been created and configured.
The symlink does not exist. Creating...
Downloading .env.example for provisioning
No provision.

 Usage: ./inmanage.sh <update|backup|clean_install|cleanup_versions|cleanup_backups> [--force] 
 Full Documentation https://github.com/DrDBanner/inmanage/#readme 

At the question for the User i have changed www-data against root.

**Comment by lakelounge** [comment] 2024-12-13 20:34
@DrDBanner 

if i start as root (git clone https://github.com/DrDBanner/inmanage.git .inmanage && .inmanage/inmanage.sh) then inmanag.sh runs to the end.

```
`.inmanage/.env.inmanage has been created and configured.
The symlink is incorrect. Updating...
Downloading .env.example for provisioning
No provision.`
```

But i can't find the symlink!? Shouldn't it be in /var/www/html/invoiceninja and point to /var/www/html/invoiceninja/.inmanage/inmanage.sh ?

If script says  "The symlink is incorrect. Updating...". What is it checking? The symlink above?

Can you confirm that this is the code in inmanage.sh which drops the error?

```
        # Handle symlink
        target="$INM_BASE_DIRECTORY.inmanage/inmanage.sh"
        link="$INM_BASE_DIRECTORY/inmanage.sh"


        # Check if the link exists
        if [ -L "$link" ]; then
            # Check if it points to the correct target
            if [ "$(readlink "$link")" == "$target" ]; then
                echo "The symlink is correct."
            else
                echo "The symlink is incorrect. Updating..."
                ln -sf "$target" "$link"
            fi
        else
            echo "The symlink does not exist. Creating..."
            ln -s "$target" "$link"
        fi
```

Thank you very much for your help!!!

**Comment by DrDBanner** [comment] 2024-12-14 15:14
Seems a debian specific thing. The variable is just empty, hence the link creation fails. On it for a fix.

**Comment by dieterth** [comment] 2024-12-14 15:40
That would match my environment. This is Debian 11.

Thank you.

**Comment by lakelounge** [comment] 2024-12-14 15:54
mine too … Debian 12 …

**Comment by DrDBanner** [comment] 2024-12-14 17:16
Problem should be fixed. Either do a git pull or wipe everything and start from scratch. Please let me know if it works.

**Comment by lakelounge** [comment] 2024-12-14 17:57
@DrDBanner 
installation of the Script works and the Symlink is created as expected! Thank you so much for your help!!!
You wrote there is a difference between ubuntu and debian? Can you shortly describe it?
Will try a clean_install tomorrow. Thank you again!

**Comment by DrDBanner** [comment] 2024-12-14 19:08
I didn't IIRC. Closing this since it's working for you. Thanks for reporting back.

**Closed by DrDBanner** 2024-12-14 19:08 UTC

**Comment by dieterth** [comment] 2024-12-15 08:27
Good Morning DrBanner,
and lakelounch,

my IN ist up and seems to be running.
At the moment i do not have access to my historical data, but there are a login Screen. :)

So far it is more in the direction that iam able to work wirh the data.
Thank you so mutch!!!
If i have full access i will report.
Best regards, Dieter
